### ISSUE TITLE
self.x11 to self.conv1?

### ISSUE THREAD

**Issue by Cjiangbpcs** [gmalivenko/gluon2pytorch#3]
Nice work! I wonder why you change the class attributes name from the original ones like self.conv1, self.bn1, etc to self.x345, self.x347? That would potentially pose problems when we need to use the class attributes after conversion.

Could you share your thoughts on how to change the script to keep the original class attributes? Thanks.

**Comment by gmalivenko** [comment]
Hello @Cjiangbpcs! 
I work on that problem (see the #1) and I will implement it as soon as possible.
It's the very first versions of the converter and I spent all time implementing new layers.

**Comment by Cjiangbpcs** [comment]
sorry I missed #1 issue, just curious, have you also worked on the conversion from pytorch2gluon?

**Comment by gmalivenko** [comment]
I thought about it, but for now it's only a plan for a further project :) PyTorch graph is much more complicated to trace.

**Comment by Cjiangbpcs** [comment]
I see, thanks. close this issue.
